# Generated by Django 3.1 on 2020-08-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
