# Generated by Django 3.1 on 2020-08-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
    ]
