# Generated by Django 3.1 on 2020-08-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reviews',
        ),
    ]
