# Generated by Django 3.1 on 2020-08-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_item_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
    ]
