# Generated by Django 3.1 on 2020-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='front',
            field=models.BooleanField(default=False),
        ),
    ]
