# Generated by Django 3.1 on 2020-08-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='front',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
