# Generated by Django 3.1 on 2020-08-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='s_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
