# Generated by Django 3.1 on 2020-08-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_category_s_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Img',
        ),
    ]
