# Generated by Django 3.1 on 2020-08-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Img',
            new_name='Image',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
