# Generated by Django 3.1 on 2020-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200813_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.TextField(),
        ),
    ]
