# Generated by Django 3.1 on 2020-08-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200813_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mover',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=100),
        ),
    ]
