# Generated by Django 3.1 on 2020-08-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_c_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
