# Generated by Django 3.1 on 2020-08-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='information',
        ),
    ]
