# Generated by Django 3.1 on 2020-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200906_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True)),
            ],
        ),
    ]
