# Generated by Django 3.1 on 2020-09-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
