# Generated by Django 3.1 on 2020-09-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_cart_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discounted_price',
        ),
    ]
