# Generated by Django 3.1 on 2020-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_cart_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='feature_product',
            field=models.BooleanField(default=False),
        ),
    ]
