# Generated by Django 3.1 on 2020-09-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_order_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
