# Generated by Django 3.1 on 2020-09-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
